
name: React Continuous Integration


# on:
#   pull_request:
#     branches: [ master ]

on:
  push:
    branches: [ master ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - run: |
          git config --global user.email ${{secrets.EMAIL_PERSONAL}} 
          git config --global user.name ${{secrets.USER_PERSONAL}}
          git remote set-url origin https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/${{secrets.USER_PERSONAL}}/basicReact.git
          npm run deploy